from django.db import models

# Create your models here.
class Userinfo(models.Model):
    name = models.CharField(max_length=100)
    link = models.CharField(max_length=200)

class Emojidata(models.Model):
    name = models.CharField(max_length=100)
    emoji = models.CharField(max_length=100)
    weight = models.FloatField()
    # PA = models.FloatField()
    # PE = models.FloatField()
    # PD = models.FloatField()
    # PH = models.FloatField()
    # PG = models.FloatField()
    # PB = models.FloatField()
    # PK = models.FloatField()
    # NA = models.FloatField()
    # NB = models.FloatField()
    # NJ = models.FloatField()
    # NH = models.FloatField()
    # PF = models.FloatField()
    # NI = models.FloatField()
    # NC = models.FloatField()
    # NG = models.FloatField()
    # NE = models.FloatField()
    # ND = models.FloatField()
    # NN = models.FloatField()
    # NK = models.FloatField()
    # NL = models.FloatField()
    # PC = models.FloatField()

class Musicdata(models.Model):
    name = models.CharField(max_length=100)
    singer = models.CharField(max_length=100)
    lyric = models.TextField(default='', max_length=10000)
    # PA = models.FloatField(default=0)
    # PE = models.FloatField(default=0)
    # PD = models.FloatField(default=0)
    # PH = models.FloatField(default=0)
    # PG = models.FloatField(default=0)
    # PB = models.FloatField(default=0)
    # PK = models.FloatField(default=0)
    # NA = models.FloatField(default=0)
    # NB = models.FloatField(default=0)
    # NJ = models.FloatField(default=0)
    # NH = models.FloatField(default=0)
    # PF = models.FloatField(default=0)
    # NI = models.FloatField(default=0)
    # NC = models.FloatField(default=0)
    # NG = models.FloatField(default=0)
    # NE = models.FloatField(default=0)
    # ND = models.FloatField(default=0)
    # NN = models.FloatField(default=0)
    # NK = models.FloatField(default=0)
    # NL = models.FloatField(default=0)
    # PC = models.FloatField(default=0)

class Usermusic(models.Model):
    user = models.CharField(max_length=100)
    music = models.CharField(max_length=100)
    singer = models.CharField(max_length=100)

class Singerdata(models.Model):
    singer = models.CharField(max_length=100)
    PA = models.FloatField(default=0)
    PE = models.FloatField(default=0)
    PD = models.FloatField(default=0)
    PH = models.FloatField(default=0)
    PG = models.FloatField(default=0)
    PB = models.FloatField(default=0)
    PK = models.FloatField(default=0)
    NA = models.FloatField(default=0)
    NB = models.FloatField(default=0)
    NJ = models.FloatField(default=0)
    NH = models.FloatField(default=0)
    PF = models.FloatField(default=0)
    NI = models.FloatField(default=0)
    NC = models.FloatField(default=0)
    NG = models.FloatField(default=0)
    NE = models.FloatField(default=0)
    ND = models.FloatField(default=0)
    NN = models.FloatField(default=0)
    NK = models.FloatField(default=0)
    NL = models.FloatField(default=0)
    PC = models.FloatField(default=0)