# Generated by Django 4.1.2 on 2022-10-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emojidata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('PA', models.FloatField()),
                ('PE', models.FloatField()),
                ('PD', models.FloatField()),
                ('PH', models.FloatField()),
                ('PG', models.FloatField()),
                ('PB', models.FloatField()),
                ('PK', models.FloatField()),
                ('NA', models.FloatField()),
                ('NB', models.FloatField()),
                ('NJ', models.FloatField()),
                ('NH', models.FloatField()),
                ('PF', models.FloatField()),
                ('NI', models.FloatField()),
                ('NC', models.FloatField()),
                ('NG', models.FloatField()),
                ('NE', models.FloatField()),
                ('ND', models.FloatField()),
                ('NN', models.FloatField()),
                ('NK', models.FloatField()),
                ('NL', models.FloatField()),
                ('PC', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Musicdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usermusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('music', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=100)),
            ],
        ),
    ]
