# Generated by Django 4.1.2 on 2022-10-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_na_emojidata_weight_remove_emojidata_nb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicdata',
            name='NA',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='musicdata',
            name='NB',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='musicdata',
            name='NC',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='musicdata',
            name='ND',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='musicdata',
            name='NE',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='musicdata',
            name='NG',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='musicdata',
            name='NH',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='musicdata',
            name='NI',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='musicdata',
            name='NJ',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='musicdata',
            name='NK',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='musicdata',
            name='NL',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='musicdata',
            name='NN',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='musicdata',
            name='PA',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='musicdata',
            name='PB',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='musicdata',
            name='PC',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='musicdata',
            name='PD',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='musicdata',
            name='PE',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='musicdata',
            name='PF',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='musicdata',
            name='PG',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='musicdata',
            name='PH',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='musicdata',
            name='PK',
            field=models.FloatField(default=0),
        ),
    ]
