# Generated by Django 4.1.2 on 2022-10-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_singerdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicdata',
            name='NA',
        ),
        migrations.RemoveField(
            model_name='musicdata',
            name='NB',
        ),
        migrations.RemoveField(
            model_name='musicdata',
            name='NC',
        ),
        migrations.RemoveField(
            model_name='musicdata',
            name='ND',
        ),
        migrations.RemoveField(
            model_name='musicdata',
            name='NE',
        ),
        migrations.RemoveField(
            model_name='musicdata',
            name='NG',
        ),
        migrations.RemoveField(
            model_name='musicdata',
            name='NH',
        ),
        migrations.RemoveField(
            model_name='musicdata',
            name='NI',
        ),
        migrations.RemoveField(
            model_name='musicdata',
            name='NJ',
        ),
        migrations.RemoveField(
            model_name='musicdata',
            name='NK',
        ),
        migrations.RemoveField(
            model_name='musicdata',
            name='NL',
        ),
        migrations.RemoveField(
            model_name='musicdata',
            name='NN',
        ),
        migrations.RemoveField(
            model_name='musicdata',
            name='PA',
        ),
        migrations.RemoveField(
            model_name='musicdata',
            name='PB',
        ),
        migrations.RemoveField(
            model_name='musicdata',
            name='PC',
        ),
        migrations.RemoveField(
            model_name='musicdata',
            name='PD',
        ),
        migrations.RemoveField(
            model_name='musicdata',
            name='PE',
        ),
        migrations.RemoveField(
            model_name='musicdata',
            name='PF',
        ),
        migrations.RemoveField(
            model_name='musicdata',
            name='PG',
        ),
        migrations.RemoveField(
            model_name='musicdata',
            name='PH',
        ),
        migrations.RemoveField(
            model_name='musicdata',
            name='PK',
        ),
        migrations.AddField(
            model_name='musicdata',
            name='lyric',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
