# Generated by Django 4.1.2 on 2022-10-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_musicdata_na_remove_musicdata_nb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicdata',
            name='lyric',
            field=models.TextField(default=''),
        ),
    ]
