# Generated by Django 4.1.2 on 2022-10-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_musicdata_lyric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicdata',
            name='lyric',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
